require 'i18n'
require 'pry-byebug'
require_relative 'config/i18n_config'
require_relative 'lib/helpers/database_loader'
require_relative 'lib/helpers/validations'
require_relative 'lib/entities/account'
require_relative 'lib/main_console'
